import { create } from 'zustand';

// Supported Languages - Currently restricted to English and Hindi only as per product specification.
// (Future area-wise / regional languages will be plugged into this schema later).
export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', icon: 'translate' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', icon: 'language' }
];

export const translations = {
  hi: {
    // Greeting
    'hi': 'नमस्ते',
    'hi,': 'नमस्ते,',

    // Navigation & Menus
    'home': 'होम',
    'dashboard': 'डैशबोर्ड',
    'wallet': 'वॉलेट',
    'passbook': 'पासबुक',
    'profile': 'प्रोफ़ाइल',
    'requests': 'रिक्वेस्ट्स',
    'pending requests': 'लंबित अनुरोध',
    'review and approve cashback claims': 'कैशबैक दावों की समीक्षा करें और स्वीकृत करें',
    'notifications': 'सूचनाएं',
    'support': 'सहायता',
    'settings': 'सेटिंग्स',
    'logout': 'लॉगआउट',
    'logout account': 'खाता लॉगआउट करें',
    'scan_qr': 'QR स्कैन करें',
    'store_qr': 'दुकान QR',
    'explore': 'एक्सप्लोर',
    'history': 'इतिहास',
    'chats': 'चैट्स',
    'chat': 'चैट',
    'bills': 'बिल',
    'store': 'स्टोर',
    'storefront': 'स्टोरफ्रंट',
    'ratings': 'रेटिंग्स',
    'reviews': 'समीक्षाएं',
    'subscription': 'सब्सक्रिप्शन',
    'transactions': 'लेन-देन',
    'customers': 'ग्राहक',
    'shop & pay later': 'शॉप एंड पे लेटर',
    'apply loan': 'लोन आवेदन',
    'soon': 'जल्द',
    'coming soon': 'जल्द आ रहा है',
    'help & support': 'मदद एवं सहायता',
    'help & faqs': 'मदद व सवाल-जवाब',
    'help & faq support': 'मदद एवं सहायता',
    'whatsapp chat': 'वॉट्सऐप चैट',
    'share store': 'दुकान शेयर करें',
    'direct whatsapp, helpline & faqs': 'डायरेक्ट वॉट्सऐप, हेल्पलाइन और FAQs',
    '24x7 active': '24x7 सक्रिय',

    // Specific Transaction Types (As per user requirement)
    // English: "Cash transaction" / "Digital transaction"
    // Hindi: "नकद लेनदेन" / "डिजिटल लेनदेन"
    'cash transaction': 'नकद लेनदेन',
    'cash transction': 'नकद लेनदेन',
    'cash transactions': 'नकद लेनदेन',
    'digital transaction': 'डिजिटल लेनदेन',
    'digital transction': 'डिजिटल लेनदेन',
    'digital transactions': 'डिजिटल लेनदेन',
    'cash': 'नकद',
    'digital': 'डिजिटल',
    'cash mode': 'नकद मोड',
    'cash mode • otp required': 'नकद मोड • OTP आवश्यक',
    'cash collection': 'नकद लेनदेन',
    'digital collection': 'डिजिटल लेनदेन',

    // Dashboard Cards & Stats
    'welcome back': 'वापसी पर स्वागत है',
    'total revenue': 'कुल राजस्व',
    'cashback given': 'दिया गया कैशबैक',
    'total txns': 'कुल लेन-देन',
    'total transactions': 'कुल लेन-देन',
    "today's sale": "आज की बिक्री",
    'sales & collections': 'बिक्री और कलेक्शन',
    'platform sales & collections': 'प्लेटफ़ॉर्म बिक्री और कलेक्शन',
    'today': 'आज',
    'weekly': 'साप्ताहिक',
    'monthly': 'मासिक',
    'yearly': 'वार्षिक',
    'this week': 'इस सप्ताह',
    'this month': 'इस महीने',
    'last month': 'पिछले महीने',
    'total sales': 'कुल बिक्री',
    'orders': 'ऑर्डर्स',
    'orders breakdown': 'ऑर्डर्स विवरण',
    'no sales found': 'कोई बिक्री नहीं मिली',
    'all store transactions': 'स्टोर के सभी लेन-देन',
    'all platform transactions': 'प्लेटफ़ॉर्म के सभी लेन-देन',
    'action required': 'कार्रवाई आवश्यक',
    'view all': 'सभी देखें',
    'recent activity': 'हालिया गतिविधि',
    'bill no:': 'बिल नं:',
    'bill no': 'बिल नं',
    'bill amount': 'बिल राशि',
    'estimated cb': 'अनुमानित कैशबैक',
    'cb:': 'कैशबैक:',
    'cashback': 'कैशबैक',
    'request': 'अनुरोध',
    'unique': 'विशिष्ट',
    'all time': 'कुल समय',
    'all caught up!': 'सभी कार्य पूर्ण हैं!',
    'no pending requests require your attention.': 'कोई लंबित अनुरोध नहीं है।',
    'no pending requests': 'कोई लंबित अनुरोध नहीं है',
    'no notifications': 'कोई सूचना नहीं है',
    'view attached receipt': 'संलग्न रसीद देखें',
    'add story': 'स्टोरी जोड़ें',
    'post daily deals & photos to nearby customers': 'आस-पास के ग्राहकों के लिए दैनिक ऑफ़र व फ़ोटो पोस्ट करें',
    'post daily offers, deals & photos to attract nearby customers': 'आस-पास के ग्राहकों के लिए दैनिक ऑफ़र, डील व फ़ोटो पोस्ट करें',
    'store stories': 'स्टोर स्टोरीज़',
    '24h deals': '24 घंटे के ऑफ़र',
    'scan customer': 'ग्राहक स्कैन करें',
    'log cash cb': 'नकद कैशबैक',
    'store qr': 'दुकान QR',
    'counter standee': 'काउंटर स्टैंडी',
    'accept cash': 'नकद स्वीकारें',
    'instant pos': 'त्वरित POS',
    'pay later': 'पे लेटर',
    'up to ₹25k': '₹25,000 तक',
    'shop & pay later': 'शॉप एंड पे लेटर',
    'credit limit: up to ₹25k': 'क्रेडिट लिमिट: ₹25,000 तक',
    'check limit': 'लिमिट देखें',
    'merchant business loan': 'मर्चेंट बिज़नेस लोन',
    '0% property collateral': '0% संपत्ति गारंटी',
    'apply loan': 'लोन आवेदन',
    'instant working capital credit limit up to ₹25,000 for your daily store purchases & stock.': 'दैनिक खरीदारी व स्टॉक के लिए ₹25,000 तक त्वरित वर्किंग कैपिटल क्रेडिट लिमिट।',
    'unsecured business growth capital up to ₹25l with 0% property collateral & micro-deductions.': 'बिना गारंटी ₹25 लाख तक व्यापार विकास लोन 0% संपत्ति गिरवी और आसान किस्तों पर।',
    'subscription required to go live': 'लाइव होने के लिए सब्सक्रिप्शन आवश्यक',
    'onboarding completed': 'ऑनबोर्डिंग पूर्ण',
    'store inactive': 'स्टोर निष्क्रिय',
    'your store is currently hidden from customer discovery and cashback issuance is paused. choose a plan to activate your store.': 'आपकी दुकान वर्तमान में ग्राहकों से छिपी है और कैशबैक रुका हुआ है। दुकान सक्रिय करने के लिए प्लान चुनें।',
    'choose subscription plan': 'सब्सक्रिप्शन प्लान चुनें',
    'subscription expired': 'सब्सक्रिप्शन समाप्त',
    'renew subscription': 'सब्सक्रिप्शन रिन्यू करें',
    'cashback blocked • store visible in 24h grace period': 'कैशबैक बंद • 24 घंटे की रियायत अवधि',
    'store inactive • hidden from users': 'स्टोर निष्क्रिय • ग्राहकों से छिपा',
    'your subscription expired. renew promptly to keep your store discoverable.': 'आपका सब्सक्रिप्शन समाप्त हो गया है। दुकान सक्रिय रखने के लिए तुरंत रिन्यू करें।',
    'your subscription expired over 24 hours ago. renew to reactivate your store.': 'आपका सब्सक्रिप्शन 24 घंटे पहले समाप्त हो चुका है। दुकान पुनः सक्रिय करने के लिए रिन्यू करें।',
    'subscription active': 'सब्सक्रिप्शन सक्रिय',
    'manage': 'प्रबंधित करें',
    'recharge your cashback wallet to enable instant cashback issuance for customers.': 'ग्राहकों को तत्काल कैशबैक देने के लिए अपने कैशबैक वॉलेट को रिचार्ज करें।',
    'counter qr standee': 'काउंटर QR स्टैंडी',
    'scan & pay via phonepe, paytm, gpay or zeebac': 'PhonePe, Paytm, GPay या ZeeBac से स्कैन व भुगतान',
    'generating qr...': 'QR बनाया जा रहा है...',
    'failed to load qr': 'QR लोड नहीं हो सका',
    'retry': 'पुनः प्रयास करें',
    'store id:': 'स्टोर ID:',
    'store id': 'स्टोर ID',
    'no recent transactions': 'हाल में कोई लेन-देन नहीं हुआ',
    'cash otp': 'नकद OTP',
    'download': 'डाउनलोड',
    'share': 'शेयर करें',

    // Wallet Page
    'payout bank account': 'निकासी बैंक खाता',
    'withdrawal money is transferred here': 'निकासी की राशि इस बैंक खाते में भेजी जाती है',
    'update bank account': 'बैंक खाता अपडेट करें',
    'add bank account': 'बैंक खाता जोड़ें',
    'no bank account linked': 'कोई बैंक खाता लिंक नहीं है',
    'link your bank account with mobile otp verification to securely withdraw your earnings.': 'अपनी कमाई सुरक्षित निकालने के लिए मोबाइल OTP सत्यापन के साथ बैंक खाता लिंक करें।',
    'earnings': 'कुल कमाई',
    'cashback sent': 'भेजा गया कैशबैक',
    'see all': 'सभी देखें',
    'no wallet activity yet.': 'अभी कोई वॉलेट गतिविधि नहीं है।',
    'store working capital': 'स्टोर वर्किंग कैपिटल',
    'maintain 30 days store transactions to unlock limit based on pan & cibil score': 'PAN और CIBIL स्कोर के आधार पर लिमिट पाने के लिए 30 दिनों का लेन-देन बनाए रखें',
    'shop & pay later • credit limit up to ₹25,000': 'शॉप एंड पे लेटर • ₹25,000 तक क्रेडिट लिमिट',
    'withdraw money': 'पैसे निकालें',
    'add money': 'पैसे जोड़ें',
    'enter amount': 'राशि दर्ज करें',
    'available balance:': 'उपलब्ध बैलेंस:',
    'quick add': 'त्वरित जोड़ें',
    'recharge cashback wallet': 'कैशबैक वॉलेट रिचार्ज',
    'platform fee': 'प्लेटफ़ॉर्म शुल्क',
    'fixed withdrawal fee': 'निश्चित निकासी शुल्क',
    'net amount': 'शुद्ध राशि',
    'proceed': 'आगे बढ़ें',
    'transferring...': 'ट्रांसफ़र हो रहा है...',
    'withdrawal request submitted': 'निकासी अनुरोध सबमिट हुआ',
    'not linked': 'लिंक नहीं है',

    // Ratings & Reviews
    'customer ratings & reviews': 'ग्राहक रेटिंग और समीक्षाएं',
    'overall rating': 'कुल रेटिंग',
    'total reviews': 'कुल समीक्षाएं',
    'verified visits': 'सत्यापित विज़िट्स',
    'reply': 'उत्तर दें',
    'replied': 'उत्तर दिया',
    'write a reply...': 'उत्तर लिखें...',
    'send reply': 'उत्तर भेजें',
    'no reviews yet': 'अभी कोई समीक्षा नहीं है',

    // Customers
    'customer directory': 'ग्राहक सूची',
    'vip patron': 'VIP ग्राहक',
    'gold member': 'गोल्ड सदस्य',
    'repeat regular': 'नियमित ग्राहक',
    'new patron': 'नया ग्राहक',
    'search customers...': 'ग्राहक खोजें...',
    'total visits': 'कुल विज़िट्स',
    'total spent': 'कुल खर्च',
    'last visit': 'अंतिम विज़िट',
    'no customers found': 'कोई ग्राहक नहीं मिला',

    // Subscription Plans
    'subscription plans': 'सब्सक्रिप्शन प्लान्स',
    'grow your store with zeebac': 'ZeeBac के साथ अपना स्टोर बढ़ाएं',
    'choose your plan': 'अपना प्लान चुनें',
    'independent store': 'स्वतंत्र स्टोर',
    'chain & brand': 'चेन एवं ब्रांड',
    'save 20%': '20% बचत',
    'current plan': 'वर्तमान प्लान',
    'renew plan': 'प्लान रिन्यू करें',
    'select plan': 'प्लान चुनें',
    'active plan': 'सक्रिय प्लान',
    'expires on': 'समाप्ति तिथि',

    // Notifications
    'mark all': 'सभी पढ़े गए चिह्नित करें',
    'no new notifications': 'कोई नई सूचना नहीं है',

    // Scan & Log Purchase
    'scan customer qr': 'ग्राहक QR स्कैन करें',
    'align customer qr within frame': 'फ्रेम के अंदर ग्राहक QR लाएं',
    'enter customer phone number': 'ग्राहक फ़ोन नंबर दर्ज करें',
    'search customer': 'ग्राहक खोजें',
    'bill / purchase amount': 'बिल / खरीदारी राशि',
    'calculate cashback': 'कैशबैक गणना करें',
    'give cashback': 'कैशबैक दें',
    'cashback given successfully': 'कैशबैक सफलतापूर्वक दिया गया',

    // Customer OTP Cashback
    'customer otp': 'कस्टमर OTP कोड',
    'customer otp code': 'कस्टमर OTP कोड',
    'verification code': 'सत्यापन कोड (OTP)',
    'enter 3-digit vendor code': '3 अंकों का वेंडर कोड दर्ज करें',
    'enter code': 'कोड दर्ज करें',
    'tell this code to customer': 'यह कोड कस्टमर को बताएं',
    'tell code to customer': 'यह कोड कस्टमर को बताएं',
    'share code to approve': 'स्वीकृत करने के लिए कोड बताएं',
    'auto-approves cashback upon entry': 'कोड दर्ज होते ही कैशबैक तुरंत स्वीकृत होगा',
    'ask the shopkeeper for the 3-digit code on their app for instant auto-approval.': 'तत्काल कैशबैक के लिए दुकानदार से उनकी ऐप में दिख रहा 3 अंकों का कोड पूछें।',
    'verify & auto-approve': 'सत्यापित व स्वीकृत करें',
    'cashback successful': 'कैशबैक सफल',
    'verified via otp': 'OTP द्वारा सत्यापित',
    'cashback processed successfully': 'कैशबैक सफलतापूर्वक प्रोसेस हुआ',
    'verified': 'सत्यापित',
    'approved': 'स्वीकृत',
    'pending': 'लंबित',
    'rejected': 'अस्वीकृत',
    'on hold': 'होल्ड पर',
    'release hold': 'होल्ड हटाएं',
    'hold': 'होल्ड',
    'approve': 'स्वीकार करें',
    'reject': 'अस्वीकार करें',
    'verifying...': 'सत्यापित हो रहा है...',
    'all': 'सभी',

    // Top Bar & Buttons
    'my qr': 'मेरा QR',
    'scan qr': 'QR स्कैन करें',
    'store qr': 'दुकान QR',
    'quick bill': 'त्वरित बिल',
    'generate bill': 'बिल बनाएं',
    'pos bill': 'POS बिल',
    'generate pos bill': 'POS बिल बनाएं',
    'recharge wallet': 'वॉलेट रिचार्ज करें',
    'cashback wallet balance is ₹0': 'कैशबैक वॉलेट बैलेंस ₹0 है',

    // Preferences & Settings
    'app language': 'ऐप भाषा',
    'select language': 'भाषा चुनें',
    'select_language': 'भाषा चुनें',
    'current language': 'वर्तमान भाषा',
    'currently available in english and hindi': 'वर्तमान में केवल हिन्दी और अंग्रेज़ी उपलब्ध हैं',
    'currently available in english & hindi': 'वर्तमान में केवल हिन्दी और अंग्रेज़ी उपलब्ध हैं',
    'push notifications': 'पुश नोटिफ़िकेशन',
    'biometric security': 'बायोमेट्रिक सुरक्षा',
    'protect withdrawals & store funds with fingerprint, face id or pin': 'फ़िंगरप्रिंट, फेस ID या PIN से निकासी और स्टोर सुरक्षित करें',
    'backup security pin:': 'बैकअप सुरक्षा PIN:',
    'configured': 'कॉन्फ़िगर है',
    'not set': 'सेट नहीं है',
    'change pin': 'PIN बदलें',
    'set pin': 'PIN सेट करें',
    'active': 'सक्रिय',
    'accounts & history': 'खाते और इतिहास',
    'withdrawal accounts': 'निकासी खाते (बैंक/UPI)',
    'rewards wallet': 'रिवार्ड्स वॉलेट',
    'my qr code': 'मेरा QR कोड',
    'refer & earn': 'रेफ़र और कमाएं',
    'save': 'सुरक्षित करें',
    'cancel': 'रद्द करें',
    'done': 'संपन्न',
    'edit': 'संपादित करें',
    'save changes': 'बदलाव सुरक्षित करें',

    // Profile & Business Info
    'store credit & growth': 'स्टोर क्रेडिट और ग्रोथ',
    'store bnpl credit': 'स्टोर BNPL क्रेडिट',
    'merchant capital': 'मर्चेंट कैपिटल',
    'apply for business loan': 'बिज़नेस लोन के लिए आवेदन करें',
    'business information': 'व्यावसायिक जानकारी',
    'business name': 'दुकान / बिज़नेस का नाम',
    'category': 'श्रेणी',
    'contact number': 'फ़ोन नंबर',
    'business email': 'बिज़नेस ईमेल',
    'store address': 'दुकान का पता',
    'description': 'विवरण',
    'operating hours': 'दुकान खुलने का समय',
    'street address / area': 'सड़क का पता / इलाका',
    'landmark': 'लैंडमार्क',
    'city': 'शहर',
    'state': 'राज्य',
    'pin code': 'पिन कोड',
    'aadhaar / pan': 'आधार / पैन',
    'gst certificate': 'GST प्रमाणपत्र',
    'uploaded': 'अपलोड किया गया',
    'not uploaded': 'अपलोड नहीं है',
    'bank details': 'बैंक खाता विवरण',
    'account holder name': 'खाताधारक का नाम',
    'bank name': 'बैंक का नाम',
    'account number': 'खाता संख्या',
    'ifsc code': 'IFSC कोड',
    'upi id': 'UPI आईडी',
    'live': 'लाइव',

    // Store Bills & Transactions Page
    'store sales & bills': 'स्टोर बिक्री और बिल',
    'total store sales (revenue)': 'कुल स्टोर बिक्री (राजस्व)',
    'approved customer orders': 'स्वीकृत ग्राहक ऑर्डर्स',
    'search by id or customer...': 'ID या ग्राहक से खोजें...',
    'no transactions found': 'कोई लेन-देन नहीं मिला',
    'try changing your filters.': 'कृपया फ़िल्टर बदल कर देखें।',

    // Passbook & Wallet
    'wallet passbook': 'वॉलेट पासबुक',
    'export': 'एक्सपोर्ट',
    'looking for store sales / revenue?': 'स्टोर बिक्री / राजस्व देखना चाहते हैं?',
    'view customer bill transactions & gross sales history': 'ग्राहकों के बिल लेन-देन व कुल बिक्री इतिहास देखें',
    'view bills': 'बिल देखें',
    'current wallet balance': 'वर्तमान वॉलेट बैलेंस',
    'wallet ledger': 'वॉलेट लेज़र',
    'all entries': 'सभी प्रविष्टियां',
    'cashback given (-₹)': 'दिया गया कैशबैक (-₹)',
    'recharges (+₹)': 'रिचार्ज (+₹)',
    'payments (+₹)': 'भुगतान (+₹)',
    'ref:': 'संदर्भ:',
    'bal:': 'शेष:',
    'loading ledger...': 'लेज़र लोड हो रहा है...',
    'no ledger entries found': 'कोई लेज़र प्रविष्टि नहीं मिली',
    'available balance': 'उपलब्ध बैलेंस',
    'add money': 'पैसे जोड़ें',
    'withdraw': 'पैसे निकालें',
    'bank account': 'बैंक खाता',
    'recent transactions': 'हालिया लेन-देन',

    // Storefront Page
    'storefront': 'स्टोरफ्रंट',
    'catalog': 'कैटलॉग',
    'catalog / products': 'उत्पाद सूची',
    'photos & videos': 'फ़ोटो और वीडियो',
    'promotions': 'ऑफ़र व प्रोमोशन',
    'store stories': 'स्टोर स्टोरीज़',
    'store catalog': 'स्टोर कैटलॉग',
    'add catalog': 'कैटलॉग जोड़ें',
    'loading catalog...': 'कैटलॉग लोड हो रहा है...',
    'store gallery': 'स्टोर गैलरी',
    'upload': 'अपलोड',
    'uploading...': 'अपलोड हो रहा है...',
    'active offers': 'सक्रिय ऑफ़र',
    'create offer': 'ऑफ़र बनाएं',
    'no active offers': 'कोई सक्रिय ऑफ़र नहीं',
    "click 'create offer' to launch promotions.": "ऑफ़र शुरू करने के लिए 'ऑफ़र बनाएं' पर क्लिक करें।",
    '24-hour stories (instagram style)': '24-घंटे की स्टोरीज़ (इंस्टाग्राम स्टाइल)',
    'temporary daily deals & updates visible on customer home feed': 'दैनिक ऑफ़र व अपडेट्स जो ग्राहकों के होम फ़ीड पर दिखते हैं',
    'daily high-engagement marketing': 'दैनिक मार्केटिंग ऑफ़र्स',
    'manage active stories': 'सक्रिय स्टोरीज़ प्रबंधित करें',
    'is this a branded product?': 'क्या यह किसी ब्रांड का उत्पाद है?',
    'select whether this product belongs to an existing or registered brand.': 'चुनें कि क्या यह उत्पाद किसी पंजीकृत ब्रांड का है।',
    'yes, this is a branded product': 'हाँ, यह एक ब्रांडेड उत्पाद है',
    'this product belongs to a brand.': 'यह उत्पाद किसी ब्रांड का है।',
    'no, this is my own/local product': 'नहीं, यह मेरा अपना / स्थानीय उत्पाद है',
    'this product is not associated with any brand.': 'यह उत्पाद किसी अन्य ब्रांड से जुड़ा नहीं है।',
    'brand information': 'ब्रांड जानकारी',
    'brand cashback': 'ब्रांड कैशबैक',
    'choose the cashback % for customers.': 'ग्राहकों के लिए कैशबैक % चुनें।',
    'live preview: customer cashback': 'लाइव पूर्वावलोकन: ग्राहक कैशबैक',
    'product details': 'उत्पाद विवरण',
    'product name *': 'उत्पाद का नाम *',
    'highlight product': 'उत्पाद हाइलाइट करें',
    'feature this product in your store.': 'अपनी दुकान पर इस उत्पाद को प्रमुखता से दिखाएं।',
    'save changes': 'बदलाव सुरक्षित करें',
    'edit product': 'उत्पाद संपादित करें',
    'catalog is empty': 'कैटलॉग खाली है',
    "click 'add catalog' to list products.": "उत्पाद जोड़ने के लिए 'कैटलॉग जोड़ें' पर क्लिक करें।",
    'in stock': 'स्टॉक में उपलब्ध',
    'out of stock': 'स्टॉक समाप्त',
    'branded': 'ब्रांडेड',
    'launch offer': 'ऑफ़र लॉन्च करें',
    'offer title': 'ऑफ़र का शीर्षक',
    'offer description': 'ऑफ़र का विवरण',
    'offer type icon': 'ऑफ़र का प्रकार',
    'gift box': 'गिफ़्ट बॉक्स',
    'add product': 'उत्पाद जोड़ें',
    'upload media': 'मीडिया अपलोड करें',
    'create promotion': 'नया ऑफ़र बनाएं',
    'no products found': 'कोई उत्पाद नहीं मिला',
    'no media uploaded': 'कोई मीडिया अपलोड नहीं है',
    'no promotions found': 'कोई ऑफ़र नहीं मिला',

    // Vendor Log & Scan Screens
    'no customer selected': 'कोई ग्राहक नहीं चुना गया',
    'find customer': 'ग्राहक खोजें',
    'transaction logged!': 'लेन-देन दर्ज हुआ!',
    'purchase from': 'खरीदारी',
    'cashback credited to customer': 'ग्राहक को कैशबैक दिया गया',
    'cashback on': 'पर कैशबैक',
    'scan': 'स्कैन',
    'log transaction': 'लेन-देन दर्ज करें',
    'customer': 'ग्राहक',
    'purchase amount': 'खरीदारी राशि',
    "enter the customer's bill amount": 'ग्राहक का बिल राशि दर्ज करें',
    'customer earns': 'ग्राहक को मिलेगा',
    'of': 'का',
    'log & credit cashback': 'दर्ज करें और कैशबैक दें',
    'processing...': 'प्रक्रिया जारी है...',
    "zeebac needs camera access to scan the customer's qr code and log their transaction.": "ग्राहक का QR कोड स्कैन करके लेन-देन दर्ज करने के लिए ZeeBac को कैमरा एक्सेस चाहिए।",
    'enable camera': 'कैमरा चालू करें',
    "i'll enter their id": 'मैं ID दर्ज करूँगा',
    'camera access denied': 'कैमरा एक्सेस अस्वीकृत',
    'starting camera…': 'कैमरा शुरू हो रहा है…',
    'allow camera access in your browser, or use the options below to enter their id manually': 'ब्राउज़र में कैमरा अनुमति दें या नीचे ग्राहक ID दर्ज करें',
    "point your camera at the customer's zeebac qr code once it starts": "शुरू होने पर ग्राहक के ZeeBac QR कोड पर कैमरा रखें",
    'camera ready': 'कैमरा तैयार है',
    'no camera access': 'कैमरा एक्सेस नहीं है',
    'enter id': 'ID दर्ज करें',
    "enter customer's zeebac id": 'ग्राहक की ZeeBac ID दर्ज करें',
    'recent customers': 'हालिया ग्राहक',
    'no recent transactions yet': 'अभी तक कोई हालिया लेन-देन नहीं',

    // Vendor Profile & Extra Sections
    'vendor profile': 'वेंडर प्रोफ़ाइल',
    'vendor account': 'वेंडर खाता',
    'switch': 'बदलें',
    'log out': 'लॉगआउट',
    'store hours': 'दुकान का समय',
    'store performance': 'स्टोर प्रदर्शन',
    'all time': 'कुल समय',
    'revenue': 'राजस्व',
    'orders': 'ऑर्डर्स',
    'documents': 'दस्तावेज़',
    'kyc & business proofs': 'KYC व व्यावसायिक प्रमाण',
    'owner pan card': 'मालिक का पैन कार्ड',
    'bank cheque': 'बैंक चेक',
    'view': 'देखें',
    'location': 'स्थान',
    'pinned for customers': 'ग्राहकों के लिए पिन किया गया',
    'owner identity': 'मालिक की पहचान',
    'kyc verified documents': 'KYC सत्यापित दस्तावेज़',
    'customer support': 'ग्राहक सहायता',
    'need help? choose a support channel to connect with our team instantly.': 'मदद चाहिए? हमारी टीम से तुरंत जुड़ने के लिए सहायता चैनल चुनें।',
    'in-app chat support': 'ऐप में चैट सहायता',
    'chat with support agents now': 'सहायता एजेंटों के साथ अभी चैट करें',
    'whatsapp support': 'वॉट्सऐप सहायता',
    'call helpline': 'हेल्पलाइन पर कॉल करें',
    'toll-free 1800-zeebac': 'टोल-फ्री 1800-ZEEBAC',
    'email support': 'ईमेल सहायता',
    'write us at support@zeebac.com': 'हमें support@zeebac.com पर लिखें',
    'counter qr': 'काउंटर QR',
    'phonepe • paytm • gpay • zeebac': 'PhonePe • Paytm • GPay • ZeeBac',
    'customers earn instant wallet cashback': 'ग्राहकों को तुरंत वॉलेट कैशबैक मिलता है',
    'gst registration certificate': 'GST पंजीकरण प्रमाणपत्र',
    'bank cheque preview': 'बैंक चेक पूर्वावलोकन',

    // Vendor Loan & Credit Models
    'merchant business loans': 'मर्चेंट बिज़नेस लोन',
    'collateral-free working capital tailored for zeebac merchant store expansion.': 'ZeeBac मर्चेंट स्टोर विस्तार के लिए बिना गारंटी का वर्किंग कैपिटल।',
    'merchant capital • coming soon': 'मर्चेंट कैपिटल • जल्द आ रहा है',
    'working capital up to ₹25,00,000': '₹25,00,000 तक वर्किंग कैपिटल',
    'unlock instant store credit lines based on your daily zeebac qr collections. zero property collateral and flexible micro-daily auto deductions from sales.': 'दैनिक ZeeBac QR कलेक्शन के आधार पर इंस्टेंट क्रेडिट लाइन। 0% संपत्ति गारंटी और बिक्री से दैनिक आसान कटौती।',
    'maximum limit': 'अधिकतम सीमा',
    'collateral': 'संपत्ति गारंटी',
    'zero security': 'बिना गारंटी',
    'repayment mode': 'भुगतान मोड',
    'daily / weekly edd': 'दैनिक / साप्ताहिक EDD',
    'kyc speed': 'KYC स्पीड',
    '100% digital': '100% डिजिटल',
    'stock & inventory': 'स्टॉक एवं इन्वेंटरी',
    'buy wholesale goods and seasonal stock without draining your cash flow.': 'कैश फ़्लो पर असर डाले बिना थोक सामान व सीज़नल स्टॉक खरीदें।',
    'sales-based micro emis': 'बिक्री आधारित माइक्रो EMI',
    'repay automatically in tiny slices from everyday store qr collections.': 'दैनिक स्टोर QR कलेक्शन से छोटी-छोटी किस्तों में स्वतः भुगतान।',
    'qr turnover score': 'QR टर्नओवर स्कोर',
    'vendor shop & pay later': 'वेंडर शॉप एंड पे लेटर',
    'coming soon • vendor credit': 'जल्द आ रहा है • वेंडर क्रेडिट',
    'maintain 30 days transactions & get credit limit upto ₹25,000': '30 दिनों का लेन-देन बनाए रखें और ₹25,000 तक क्रेडिट लिमिट पाएं',
    'credit limit': 'क्रेडिट लिमिट',
    'upto ₹25,000': '₹25,000 तक',
    '0% (collateral-free)': '0% (बिना गारंटी)',
    '0% (zero security)': '0% (बिना गारंटी)',
    'credit line limit': 'क्रेडिट लाइन लिमिट',
    'up to ₹25 lakhs': '₹25 लाख तक',
    'zeebac merchant business loan': 'ZeeBac मर्चेंट बिज़नेस लोन',
    'collateral-free working capital loan up to ₹25 lakhs to expand your store & purchase inventory.': 'दुकान विस्तार और स्टॉक खरीदने के लिए ₹25 लाख तक बिना गारंटी लोन।',
    'back to dashboard': 'डैशबोर्ड पर वापस जाएं',
    'pre-register for early merchant credit': 'मर्चेंट क्रेडिट के लिए पहले रजिस्टर करें',
    'business / store name': 'व्यापार / दुकान का नाम',
    'required loan amount': 'आवश्यक लोन राशि',
    'primary purpose': 'प्राथमिक उद्देश्य',
    'join merchant vip waitlist': 'मर्चेंट VIP प्रतीक्षा सूची में शामिल हों',
    'store pre-registered! 🎉': 'दुकान पहले से पंजीकृत हो गई! 🎉',
    'licensed nbfcs': 'लाइसेंस प्राप्त NBFCs',
    'social links': 'सोशल लिंक्स',
    'website': 'वेबसाइट',
    'instagram': 'इंस्टाग्राम',
    'facebook': 'फेसबुक',
    'whatsapp': 'व्हाट्सएप',
    'switch to customer app': 'कस्टमर ऐप पर जाएं',

    // Vendor POS & Cash Simulation
    'cash bill barcode (> ₹1,000)': 'नकद बिल बारकोड (> ₹1,000)',
    'cash bill barcode': 'नकद बिल बारकोड',
    'instant withdrawable cashback': 'तत्काल निकासी योग्य कैशबैक',
    'enter cash bill amount above ₹1,000 to generate a one-time barcode for the customer to scan for instant cashback.': 'ग्राहक को तत्काल कैशबैक के लिए स्कैन करने हेतु ₹1,000 से अधिक नकद बिल राशि दर्ज करें।',
    'cash bill amount (₹)': 'नकद बिल राशि (₹)',
    'customer cashback': 'ग्राहक कैशबैक',
    'generating barcode...': 'बारकोड बनाया जा रहा है...',
    'generate cash qr barcode': 'नकद QR बारकोड बनाएं',
    'one-time cash qr': 'एकमुश्त नकद QR',
    'instant withdrawable': 'तत्काल निकासी योग्य',
    'ask customer to scan this qr code with scan & pay in zeebac app to gain instant withdrawable cashback!': 'ग्राहक से कहें कि वे तुरंत निकासी योग्य कैशबैक पाने के लिए ZeeBac ऐप में स्कैन और पे से इस QR को स्कैन करें!',
    'generate another bill': 'दूसरा बिल बनाएं',
    'bill': 'बिल',
    'cashback': 'कैशबैक',

    // Vendor Customers & Loyalty
    'track customer visits, lifetime spend, verified reviews, and patron loyalty tiers': 'ग्राहक विज़िट, कुल खर्च, सत्यापित समीक्षाएं और वफादारी स्तर ट्रैक करें',
    'repeat regular': 'नियमित ग्राहक',
    'vip patron': 'VIP ग्राहक',
    'gold member': 'गोल्ड सदस्य',
    'new patron': 'नए ग्राहक',
    'high-value loyalty': 'उच्च मूल्य वफादारी',
    'search by name, zeebac id, or mobile number...': 'नाम, ZeeBac ID या मोबाइल नंबर से खोजें...',
    'all customers': 'सभी ग्राहक',
    'vip / gold': 'VIP / गोल्ड',
    'regulars (2+)': 'नियमित (2+)',
    'new patrons': 'नए ग्राहक',
    'left review ⭐': 'समीक्षा दी ⭐',
    'loading customer transaction data...': 'ग्राहक लेन-देन डेटा लोड हो रहा है...',
    'no matching customers found': 'कोई मेल खाने वाला ग्राहक नहीं मिला',
    'try adjusting your search query or filter criteria.': 'अपनी खोज या फ़िल्टर बदलकर पुनः प्रयास करें।',
    'transactions logged through your qr or cashier will appear here.': 'आपके QR या कैशियर के माध्यम से दर्ज लेन-देन यहां दिखाई देंगे।',
    'no review yet': 'अभी कोई समीक्षा नहीं',
    'visits': 'विज़िट्स',
    'lifetime spend': 'कुल खर्च',
    'last seen': 'अंतिम बार देखा गया',

    // Vendor Ratings & Reviews
    '5 stars': '5 स्टार',
    '4 stars': '4 स्टार',
    '3 stars': '3 स्टार',
    'unknown user': 'अज्ञात उपयोगकर्ता',
    'your response': 'आपका जवाब',
    'write a response to this customer...': 'इस ग्राहक को जवाब लिखें...',
    'sending...': 'भेजा जा रहा है...',
    'send reply': 'जवाब भेजें',
    'no reviews found': 'कोई समीक्षा नहीं मिली',
    'try changing your filters.': 'फ़िल्टर बदलकर पुनः प्रयास करें।',
    'reply': 'जवाब दें',
    'cancel': 'रद्द करें',

    // Vendor Support
    'vendor support': 'विक्रेता सहायता',
    'we are here to help you grow your business.': 'हम आपके व्यापार को बढ़ाने में मदद के लिए उपलब्ध हैं।',
    'call helpline': 'हेल्पलाइन पर कॉल करें',
    'toll-free': 'टोल-फ़्री',
    'merchant help': 'व्यापारी सहायता',
    'my support tickets': 'मेरे सहायता टिकट',
    '+ new ticket': '+ नया टिकट',
    'subject': 'विषय',
    'message': 'संदेश',
    'describe your issue...': 'अपनी समस्या का विवरण दें...',
    'e.g., issue with wallet withdrawal': 'उदा., वॉलेट निकासी में समस्या',
    'submit ticket': 'टिकट सबमिट करें',
    'submitting...': 'सबमिट हो रहा है...',
    'loading tickets...': 'टिकट लोड हो रहे हैं...',
    'no tickets yet': 'अभी कोई टिकट नहीं है',
    'resolved': 'समाधान हुआ',
    'open': 'प्रगति पर',
    'zeebac support': 'ZeeBac सहायता',
    'no faqs available': 'कोई FAQs उपलब्ध नहीं हैं',

    // Vendor Passbook & Transactions
    'wallet passbook': 'वॉलेट पासबुक',
    'looking for store sales / revenue?': 'दुकान की बिक्री / राजस्व खोज रहे हैं?',
    'view customer bill transactions & gross sales history': 'ग्राहक बिल लेन-देन व कुल बिक्री इतिहास देखें',
    'view bills': 'बिल देखें',
    'current wallet balance': 'वर्तमान वॉलेट बैलेंस',
    'wallet ledger': 'वॉलेट लेज़र',
    'export': 'एक्सपोर्ट',
    'all entries': 'सभी प्रविष्टियां',
    'cashback given (-₹)': 'दिया गया कैशबैक (-₹)',
    'recharges (+₹)': 'रिचार्ज (+₹)',
    'store sales & bills': 'दुकान बिक्री और बिल',
    'total store sales (revenue)': 'कुल दुकान बिक्री (राजस्व)',
    'approved customer orders': 'स्वीकृत ग्राहक ऑर्डर्स',
    'search by id or customer...': 'ID या ग्राहक से खोजें...',

    // Vendor Chat
    'messages': 'संदेश',
    'search by customer name...': 'ग्राहक के नाम से खोजें...',
    'no messages yet': 'अभी कोई संदेश नहीं है',
    'when customers contact you, chats will appear here.': 'जब ग्राहक संपर्क करेंगे, बातचीत यहां दिखाई देगी।',
    'type a message...': 'संदेश टाइप करें...',
    'uploading image...': 'फ़ोटो अपलोड हो रही है...',
    'voice call': 'वॉयस कॉल',
    'missed voice call': 'मिस्ड वॉयस कॉल',
    'declined call': 'अस्वीकृत कॉल',
    'seen': 'देखा गया',
    'sent': 'भेजा गया',
    'you:': 'आप:',
    'online': 'ऑनलाइन',
    'call customer': 'ग्राहक को कॉल करें',
    'start a conversation...': 'बातचीत शुरू करें...',

    // Vendor Stories Modal
    'create story': 'स्टोरी बनाएं',
    'active stories': 'सक्रिय स्टोरीज़',
    'post daily flash deals and updates to attract nearby customers': 'दैनिक ऑफ़र व अपडेट पोस्ट करके आस-पास के ग्राहकों को आकर्षित करें',
    'tap canvas to upload photo or video': 'फ़ोटो या वीडियो अपलोड करने के लिए टैप करें',
    'tap canvas to change media': 'फ़ाइल बदलने के लिए टैप करें',
    'choose photo or video': 'फ़ोटो या वीडियो चुनें',
    'photo selected': 'फ़ोटो चुनी गई',
    'video selected': 'वीडियो चुना गया',
    'offer highlight': 'ऑफ़र हाइलाइट',
    'special offer': 'विशेष ऑफ़र',
    'custom offer tag': 'कस्टम ऑफ़र टैग',
    'deal caption / message': 'ऑफ़र संदेश / विवरण',
    'publish story (24h)': 'स्टोरी प्रकाशित करें (24 घंटे)',
    'publishing...': 'प्रकाशित हो रही है...',
    'who viewed': 'किसने देखा',
    'no viewers yet': 'अभी कोई दर्शक नहीं',
    'when nearby customers browse your store\'s 24h story on their feed, their names will show here in real-time.': 'जब ग्राहक आपकी 24 घंटे की स्टोरी देखेंगे, उनके नाम यहां दिखाई देंगे।',
    'delete story': 'स्टोरी हटाएं',
    'your store': 'आपकी दुकान',
    '24h live': '24 घंटे लाइव',
    'tap to change photo': 'फ़ोटो बदलने के लिए टैप करें',
    'change': 'बदलें',
    'remove': 'हटाएं',
    'add your deal message or store update...': 'अपना ऑफ़र या दुकान का अपडेट लिखें...',
    'store stories': 'दुकान की स्टोरीज़',
    'story viewers': 'स्टोरी देखने वाले',
    'search viewer by name...': 'नाम से दर्शक खोजें...',
    'viewed': 'देखा गया',
    'tap to add photo or video': 'फ़ोटो या वीडियो जोड़ने के लिए टैप करें',
    'custom +': 'कस्टम +',
    'story caption': 'स्टोरी कैप्शन',
    'theme accent': 'थीम एक्सेंट',
    'upload photo to publish': 'प्रकाशित करने के लिए फ़ोटो अपलोड करें',
    'visible to nearby customers for exactly 24 hours': 'आस-पास के ग्राहकों को ठीक 24 घंटे दिखेगा',
    'loading stories...': 'स्टोरीज़ लोड हो रही हैं...',
    'no active stories': 'कोई सक्रिय स्टोरी नहीं है',
    'create your first story': 'अपनी पहली स्टोरी बनाएं',
    'who seen': 'किसने देखा',
    'view names': 'नाम देखें',
    'auto-expires in 24 hours': '24 घंटे में स्वतः समाप्त',
    'write your deal details, discount message, or announcement...': 'अपने ऑफ़र, छूट या घोषणा का विवरण लिखें...',
    'add a story to showcase today\'s deals & updates to nearby shoppers on the zeebac app!': 'ZeeBac ऐप पर ग्राहकों को आज के ऑफ़र दिखाने के लिए स्टोरी जोड़ें!',

    // Vendor Storefront & Catalog
    'store catalog': 'दुकान कैटलॉग',
    'storefront': 'स्टोरफ़्रंट',
    'catalog / products': 'कैटलॉग / उत्पाद',
    'photos & videos': 'फ़ोटो और वीडियो',
    'promotions': 'प्रचार और ऑफ़र',
    'add catalog': 'कैटलॉग जोड़ें',
    'loading catalog...': 'कैटलॉग लोड हो रहा है...',
    'branded': 'ब्रांडेड',
    'in stock': 'स्टॉक में',
    'out of stock': 'स्टॉक समाप्त',
    'highlight': 'हाइलाइट',
    'delete product': 'उत्पाद हटाएं',
    'catalog is empty': 'कैटलॉग खाली है',
    "click 'add catalog' to list products.": "उत्पाद जोड़ने के लिए 'कैटलॉग जोड़ें' पर क्लिक करें।",
    'store gallery': 'दुकान गैलरी',
    'upload': 'अपलोड',
    'uploading...': 'अपलोड हो रहा है...',
    'is this a branded product?': 'क्या यह किसी ब्रांड का उत्पाद है?',
    'select whether this product belongs to an existing or registered brand.': 'चुनें कि क्या यह उत्पाद किसी मौजूदा या पंजीकृत ब्रांड का है।',
    'yes, this is a branded product': 'हाँ, यह एक ब्रांडेड उत्पाद है',
    'this product belongs to a brand.': 'यह उत्पाद किसी ब्रांड का है।',
    'no, this is my own/local product': 'नहीं, यह मेरा अपना/स्थानीय उत्पाद है',
    'this product is not associated with any brand.': 'यह उत्पाद किसी ब्रांड से जुड़ा नहीं है।',
    'brand information': 'ब्रांड विवरण',
    'brand logo *': 'ब्रांड लोगो *',
    'brand name *': 'ब्रांड का नाम *',
    'brand owner / company name *': 'ब्रांड स्वामी / कंपनी का नाम *',
    'brand website (optional)': 'ब्रांड वेबसाइट (वैकल्पिक)',
    'brand description': 'ब्रांड विवरण',
    'brand email': 'ब्रांड ईमेल',
    'brand contact number': 'ब्रांड संपर्क नंबर',
    'brand cashback': 'ब्रांड कैशबैक',
    'choose the cashback % for customers.': 'ग्राहकों के लिए कैशबैक % चुनें।',
    'live preview: customer cashback': 'लाइव पूर्वावलोकन: ग्राहक कैशबैक',
    'product details': 'उत्पाद विवरण',
    'product image *': 'उत्पाद की फ़ोटो *',
    'product name *': 'उत्पाद का नाम *',
    'select category': 'श्रेणी चुनें',
    'electronics': 'इलेक्ट्रॉनिक्स',
    'fashion & apparel': 'फैशन और परिधान',
    'groceries': 'किराना और राशन',
    'home & furniture': 'होम और फर्नीचर',
    'beauty & personal care': 'सौंदर्य और व्यक्तिगत देखभाल',
    'other': 'अन्य',
    'sku (optional)': 'SKU (वैकल्पिक)',
    'price (₹) *': 'मूल्य (₹) *',
    'discount price (₹)': 'छूट मूल्य (₹)',
    'stock quantity': 'स्टॉक मात्रा',
    'product description': 'उत्पाद विवरण',
    'highlight product': 'उत्पाद हाइलाइट करें',
    'feature this product in your store.': 'इस उत्पाद को अपनी दुकान पर प्रमुखता से दिखाएं।',
    'step': 'चरण',
    'save changes': 'बदलाव सहेजें',
    'add product': 'उत्पाद जोड़ें',
    'edit product': 'उत्पाद संपादित करें',
    'create promotion': 'प्रचार बनाएं',
    'offer title': 'ऑफ़र शीर्षक',
    'offer description': 'ऑफ़र विवरण',
    'offer type icon': 'ऑफ़र प्रकार आइकन',
    'gift box': 'उपहार बॉक्स',
    'launch offer': 'ऑफ़र लॉन्च करें',
    'tap to upload file': 'फ़ाइल अपलोड करने के लिए टैप करें',

    // Vendor Wallet Modals
    'wallet & payouts': 'वॉलेट और भुगतान',
    'cashback wallet': 'कैशबैक वॉलेट',
    'available balance': 'उपलब्ध बैलेंस',
    'add funds': 'पैसे जोड़ें',
    'withdraw funds': 'पैसे निकालें',
    'enter amount': 'राशि दर्ज करें',
    'quick select': 'त्वरित चयन',
    'proceed to pay': 'भुगतान के लिए आगे बढ़ें',
    'destination bank account': 'गंतव्य बैंक खाता',
    'bank account required': 'बैंक खाता आवश्यक',
    'you must link and verify your bank account with otp before requesting a withdrawal.': 'निकासी से पहले बैंक खाते को OTP से सत्यापित करना आवश्यक है।',
    'link bank account now': 'बैंक खाता अभी जोड़ें',
    'payout breakdown': 'भुगतान विवरण',
    'withdrawal amount:': 'निकासी राशि:',
    'withdrawal fee:': 'निकासी शुल्क:',
    'platform fee (2%):': 'प्लेटफ़ॉर्म शुल्क (2%):',
    'total fee deduction:': 'कुल शुल्क कटौती:',
    'net bank payout:': 'शुद्ध बैंक भुगतान:',
    'transferred to linked bank': 'लिंक किए गए बैंक में भेजा जाएगा',
    'withdraw net': 'शुद्ध निकासी',
    'withdrawals are reviewed by admin and credited to your verified bank account within 24-48 business hours.': 'निकासी की एडमिन द्वारा समीक्षा की जाती है और 24-48 कार्य घंटों में आपके खाते में जमा की जाती है।',
    'withdrawal submitted!': 'निकासी अनुरोध सबमिट हो गया!',
    'your request has been received and will be processed to your bank within 24-48 business hours.': 'आपका अनुरोध प्राप्त हो गया है और 24-48 कार्य घंटों में बैंक में जमा कर दिया जाएगा।',
    'transaction receipt': 'लेन-देन रसीद',
    'gross withdrawal:': 'सकल निकासी:',
    'net bank transfer:': 'शुद्ध बैंक ट्रांसफर:',
    'destination account': 'गंतव्य खाता',
    'done & return to wallet': 'पूर्ण व वॉलेट पर लौटें',
    'link bank account': 'बैंक खाता लिंक करें',
    'update bank account': 'बैंक खाता अपडेट करें',
    'verify mobile otp': 'मोबाइल OTP सत्यापित करें',
    'secure bank details for withdrawal payouts': 'निकासी के लिए सुरक्षित बैंक विवरण',
    'two-step security verification': 'दो-चरणीय सुरक्षा सत्यापन',
    'account holder name *': 'खाताधारक का नाम *',
    'bank name *': 'बैंक का नाम *',
    'account number *': 'खाता संख्या *',
    'confirm account *': 'खाता संख्या पुनः दर्ज करें *',
    'ifsc code *': 'IFSC कोड *',
    'upi id (optional)': 'UPI ID (वैकल्पिक)',
    'continue to otp verification': 'OTP सत्यापन के लिए आगे बढ़ें',
    'enter verification code': 'सत्यापन कोड दर्ज करें',
    '4-digit otp': '4-अंकीय OTP',
    'edit bank details': 'बैंक विवरण बदलें',
    'resend code': 'कोड पुनः भेजें',
    'verify & link account': 'सत्यापित करें और खाता जोड़ें',

    // Vendor Subscription
    'current subscription status': 'वर्तमान सब्सक्रिप्शन स्थिति',
    'visible on map & search': 'मैप व खोज पर दृश्यमान',
    'hidden from discovery': 'ग्राहकों से छिपा हुआ',
    'cashback wallet balance': 'कैशबैक वॉलेट बैलेंस',
    '1 month plan': '1 महीने का प्लान',
    'flexible option': 'लचीला विकल्प',
    'pay month-to-month with complete flexibility.': 'पूर्ण स्वतंत्रता के साथ मासिक भुगतान करें।',
    'welcome offer: +10 days extra validity free!': 'स्वागत ऑफ़र: +10 दिन अतिरिक्त वैधता मुफ्त!',
    'purchase your first subscription today and automatically receive +10 bonus days added to your plan validity upon checkout!': 'आज अपना पहला सब्सक्रिप्शन खरीदें और चेकआउट पर स्वतः +10 अतिरिक्त दिन वैधता पाएं!',
    'new merchant special': 'नए विक्रेता हेतु विशेष',
    'store is currently inactive / hidden': 'स्टोर वर्तमान में निष्क्रिय / छिपा है',
    'your store does not appear in customer searches or map listings. choose a payment method below to activate your store instantly.': 'आपकी दुकान खोज या मैप पर नहीं दिखती। दुकान तुरंत सक्रिय करने के लिए प्लान चुनें।',
    'notice: cashback wallet balance is ₹0. cashback requests are paused until you recharge.': 'सूचना: कैशबैक वॉलेट ₹0 है। रिचार्ज होने तक कैशबैक अनुरोध रुके रहेंगे।',

    // Vendor Profile
    'social links': 'सोशल लिंक्स',
    'website': 'वेबसाइट',
    'instagram': 'इंस्टाग्राम',
    'facebook': 'फेसबुक',
    'whatsapp': 'वॉट्सऐप',
    'credit limit up to ₹25,000 based on pan & cibil': 'PAN व CIBIL के आधार पर ₹25,000 तक क्रेडिट लिमिट',
    'up to ₹25l collateral-free • auto daily sales deductions': '₹25 लाख तक बिना गारंटी • दैनिक बिक्री से आसान कटौती',
    'apply for business loan': 'बिज़नेस लोन के लिए आवेदन करें',
    'app language': 'ऐप की भाषा',
    'currently available in english & hindi': 'वर्तमान में अंग्रेज़ी और हिन्दी में उपलब्ध',
    'switch to customer app': 'कस्टमर ऐप में बदलें',
    'switch to customer app / यूजर ऐप खोलें': 'कस्टमर ऐप में बदलें',

    // Storefront Form Labels & Categories
    'brand logo *': 'ब्रांड लोगो *',
    'brand name *': 'ब्रांड का नाम *',
    'brand owner / company name *': 'ब्रांड मालिक / कंपनी का नाम *',
    'brand website (optional)': 'ब्रांड वेबसाइट (वैकल्पिक)',
    'brand description': 'ब्रांड का विवरण',
    'brand email': 'ब्रांड का ईमेल',
    'brand contact number': 'ब्रांड संपर्क नंबर',
    'product image *': 'उत्पाद की फ़ोटो *',
    'select category': 'श्रेणी चुनें',
    'electronics': 'इलेक्ट्रॉनिक्स',
    'fashion & apparel': 'फैशन और परिधान',
    'groceries': 'किराना और ग्रोसरी',
    'home & furniture': 'घर और फर्नीचर',
    'beauty & personal care': 'सौंदर्य और व्यक्तिगत देखभाल',
    'other': 'अन्य',
    'sku (optional)': 'SKU (वैकल्पिक)',
    'price (₹) *': 'मूल्य (₹) *',
    'discount price (₹)': 'छूट मूल्य (₹)',
    'stock quantity': 'स्टॉक मात्रा',
    'product description': 'उत्पाद का विवरण',
    'tap to upload file': 'फ़ाइल अपलोड करने के लिए टैप करें',

    // User Side: Profile & Subviews
    'my profile': 'मेरी प्रोफ़ाइल',
    'identity verified': 'पहचान सत्यापित',
    'kyc done': 'KYC पूर्ण',
    'aadhaar': 'आधार',
    'pan card': 'पैन कार्ड',
    'total cashback': 'कुल कैशबैक',
    'in your wallet': 'आपके वॉलेट में',
    'pending audits': 'लंबित ऑडिट्स',
    'awaiting review': 'समीक्षाधीन',
    'request': 'अनुरोध',
    'requests': 'अनुरोध',
    'manage linked bank details & upi': 'लिंक्ड बैंक विवरण और UPI प्रबंधित करें',
    'check balance status, withdrawal & rewards': 'बैलेंस, निकासी और पुरस्कार देखें',
    'receive cashback or payments instantly': 'तुरंत कैशबैक या भुगतान प्राप्त करें',
    'get ₹150 reward for each friend you invite': 'हर आमंत्रित मित्र पर ₹150 पुरस्कार पाएं',
    'preferences': 'प्राथमिकताएं',
    'alerts on cashback audits and rewards': 'कैशबैक ऑडिट और पुरस्कारों के अलर्ट',
    'protect cashouts with fingerprint, face id or pin': 'फ़िंगरप्रिंट, फेस ID या PIN से निकासी सुरक्षित करें',
    'backup pin:': 'बैकअप PIN:',
    'configured ✅': 'कॉन्फ़िगर है ✅',
    'not set': 'सेट नहीं है',
    'change pin': 'PIN बदलें',
    'set pin': 'PIN सेट करें',
    'whatsapp chat & customer care helpline': 'वॉट्सऐप चैट और कस्टमर केयर हेल्पलाइन',
    'change profile photo': 'प्रोफ़ाइल फ़ोटो बदलें',
    'take photo': 'फ़ोटो लें',
    'choose gallery': 'गैलरी से चुनें',
    'remove photo': 'फ़ोटो हटाएं',
    'set security pin': 'सुरक्षा PIN सेट करें',
    'change security pin': 'सुरक्षा PIN बदलें',
    'set 4-digit pin': '4-अंकीय PIN सेट करें',
    'change 4-digit pin': '4-अंकीय PIN बदलें',
    'secures withdrawals & biometrics': 'निकासी और बायोमेट्रिक्स सुरक्षित करता है',
    'create a secret 4-digit pin for withdrawal authentication.': 'निकासी सत्यापन के लिए 4 अंकों का गुप्त PIN बनाएं।',
    'verify your current 4-digit pin and choose a new one.': 'अपना वर्तमान 4-अंकीय PIN सत्यापित करें और नया PIN चुनें।',
    'current 4-digit pin': 'वर्तमान 4-अंकीय PIN',
    'enter 4-digit pin': '4-अंकीय PIN दर्ज करें',
    'new 4-digit pin': 'नया 4-अंकीय PIN',
    'confirm 4-digit pin': '4-अंकीय PIN की पुष्टि करें',
    '4-digit pins match perfectly': '4-अंकीय PIN मेल खाते हैं ✅',
    'pins do not match': 'PIN मेल नहीं खा रहे हैं ❌',
    'save pin': 'PIN सुरक्षित करें',
    'update pin': 'PIN अपडेट करें',
    'strictly 4 digits. never share your security pin with anyone.': 'केवल 4 अंक। अपना सुरक्षा PIN कभी किसी के साथ साझा न करें।',
    'backup for biometrics & cashouts': 'बायोमेट्रिक्स और निकासी का बैकअप',
    'current pin': 'वर्तमान PIN',
    'enter current pin': 'वर्तमान PIN दर्ज करें',
    'create pin (4-8 digits)': 'PIN बनाएं (4 अंक)',
    'new pin (4-8 digits)': 'नया PIN (4 अंक)',
    'confirm pin': 'PIN की पुष्टि करें',
    're-enter pin': 'PIN पुनः दर्ज करें',
    'save & continue': 'सुरक्षित करें और आगे बढ़ें',
    'edit profile': 'प्रोफ़ाइल संपादित करें',
    'full name': 'पूरा नाम',
    'phone number': 'फ़ोन नंबर',
    'email address': 'ईमेल पता',
    'phone number cannot be modified.': 'फ़ोन नंबर बदला नहीं जा सकता।',
    'save changes': 'बदलाव सुरक्षित करें',
    'linked accounts': 'लिंक्ड खाते',
    'bank account number': 'बैंक खाता संख्या',
    're-enter account number': 'खाता संख्या पुनः दर्ज करें',
    'verify with mobile otp': 'मोबाइल OTP से सत्यापित करें',
    'sending otp...': 'OTP भेजा जा रहा है...',
    'verify bank linking': 'बैंक लिंकिंग सत्यापित करें',
    'enter the 4-digit code sent to your registered mobile number:': 'अपने पंजीकृत मोबाइल नंबर पर भेजा गया 4 अंकों का कोड दर्ज करें:',
    'resend otp in': 'पुनः OTP भेजें',
    'resend otp via sms': 'SMS द्वारा पुनः OTP भेजें',
    'confirm & link account': 'पुष्टि करें और खाता लिंक करें',
    'my zeebac qr': 'मेरा ZeeBac QR',
    'zeebac id': 'ZeeBac ID',
    'copy': 'कॉपी करें',
    'copied': 'कॉपी हो गया',
    'download': 'डाउनलोड',
    'share': 'शेयर करें',
    'show this qr to vendors for instant wallet cashback transactions. no receipt needed!': 'तत्काल वॉलेट कैशबैक लेन-देन के लिए यह QR दुकानदारों को दिखाएं। रसीद की आवश्यकता नहीं!',
    'refer & earn': 'रेफ़र और कमाएं',
    'instant cash reward': 'तत्काल नकद पुरस्कार',
    'friends invited': 'मित्र आमंत्रित',
    'total bonus earned': 'कुल अर्जित बोनस',
    'your unique referral code': 'आपका विशिष्ट रेफ़रल कोड',
    'copy code': 'कोड कॉपी करें',
    'invite link (auto-applies code)': 'आमंत्रण लिंक (कोड स्वतः लागू होगा)',
    'copy link': 'लिंक कॉपी करें',
    'invited friends': 'आमंत्रित मित्र',
    'how referral payout works': 'रेफ़रल भुगतान कैसे काम करता है',
    'share your invite link': 'अपना आमंत्रण लिंक साझा करें',
    'friend completes first cashback': 'मित्र पहला कैशबैक प्राप्त करता है',
    'instant admin wallet payout': 'तत्काल एडमिन वॉलेट भुगतान',
    'share invite link & earn': 'आमंत्रण लिंक साझा करें और कमाएं',
    'cashback audits & requests': 'कैशबैक ऑडिट व अनुरोध',
    'all requests': 'सभी अनुरोध',
    'track verification timeline': 'सत्यापन समयसीमा ट्रैक करें',
    'no pending requests found': 'कोई लंबित अनुरोध नहीं मिला',
    'no requests found': 'कोई अनुरोध नहीं मिला',
    'bill receipt': 'बिल रसीद',
    'cash claim': 'नकद दावा',
    'pending audit': 'लंबित ऑडिट',
    'declined': 'अस्वीकृत',
    'held (review)': 'होल्ड (समीक्षाधीन)',

    // User Side: Home Screen
    "let's find you some cashback today": 'आइए आज आपके लिए कैशबैक ढूंढें',
    'view balance': 'बैलेंस देखें',
    'scan & pay': 'स्कैन व भुगतान',
    'upload bill': 'बिल अपलोड',
    'find vendor': 'दुकान खोजें',
    'shop & pay later': 'शॉप व पे लेटर',
    'claim by utr': 'UTR से दावा',
    'mobile recharge': 'मोबाइल रिचार्ज',
    'personal loan': 'पर्सनल लोन',
    'recently visited': 'हाल में देखी गई दुकानें',
    'nearby partner vendors': 'आस-पास के पार्टनर स्टोर्स',
    'see all': 'सभी देखें',
    'no nearby vendors yet': 'अभी कोई नजदीकी दुकान नहीं मिली',
    'explore the full directory to find partner stores near you': 'अपने आस-पास पार्टनर स्टोर खोजने के लिए पूरी सूची देखें',
    'browse explore': 'एक्सप्लोर देखें',
    'km away': 'किमी दूर',
    'nearby': 'आस-पास',
    'flat': 'फ़्लैट',

    // User Side: Wallet & Passbook
    'total cashback reward': 'कुल कैशबैक पुरस्कार',
    'recent wallet activity': 'हालिया वॉलेट गतिविधि',
    'no activity yet': 'अभी कोई गतिविधि नहीं है',
    'your cashback credits and cashouts will show up here': 'आपके कैशबैक क्रेडिट और निकासी यहां दिखाई देंगे',
    'cashback requests': 'कैशबैक अनुरोध',
    'view status of submitted bills & receipts': 'जमा किए गए बिलों व रसीदों की स्थिति देखें',
    'withdrawal': 'पैसे निकालें',
    'rewards': 'रिवार्ड्स',
    'claim upi cashback': 'UPI कैशबैक का दावा करें',
    'verify & claim cashback': 'सत्यापित करें और कैशबैक पाएं',
    'balance & history': 'बैलेंस एवं इतिहास',
    'your accounts': 'आपके खाते',
    'zeebac wallet': 'ZeeBac वॉलेट',
    'check balance': 'बैलेंस चेक करें',
    'missing cashback?': 'कैशबैक नहीं मिला?',
    'upload your receipt to claim it': 'दावा करने के लिए अपनी रसीद अपलोड करें',
    'payment history': 'भुगतान इतिहास',
    'search by name, cashback or tag...': 'नाम, कैशबैक या टैग से खोजें...',
    'all transactions': 'सभी लेन-देन',
    'gained cashback': 'प्राप्त कैशबैक',
    'all activity (cashback, withdrawal, perks)': 'सभी गतिविधियां (कैशबैक, निकासी, लाभ)',
    'current balance': 'वर्तमान बैलेंस',
    'gained cashback only': 'केवल प्राप्त कैशबैक',
    'total cashback earned': 'कुल अर्जित कैशबैक',
    'credited': 'जमा हुआ',
    'debited': 'निकाला गया',
    'no gained cashback found': 'कोई प्राप्त कैशबैक नहीं मिला',
    'no transactions found': 'कोई लेन-देन नहीं मिला',
    'shop at partner stores or scan receipts to earn instant cashback!': 'तत्काल कैशबैक पाने के लिए पार्टनर स्टोर्स पर खरीदारी करें या रसीदें स्कैन करें!',
    'your wallet transactions and withdrawals will show here.': 'आपके वॉलेट लेन-देन और निकासी यहां दिखाई देंगे।',

    // User Side: Explore Screen
    'search local shops and brands...': 'स्थानीय दुकानें और ब्रांड खोजें...',
    'no vendors found': 'कोई स्टोर नहीं मिला',
    'try searching for other categories or names': 'अन्य श्रेणियों या नामों से खोजने का प्रयास करें',
    'tap to view store': 'स्टोर देखने के लिए टैप करें',
    'find deals near you': 'अपने आस-पास के ऑफ़र खोजें',
    'allow location access to see the best cashback offers from stores around you.': 'अपने आस-पास के स्टोर से सर्वोत्तम कैशबैक ऑफ़र देखने के लिए स्थान एक्सेस की अनुमति दें।',

    // User Side: Cashout & Security
    'cashout to bank': 'बैंक में निकासी करें',
    'available for cashout': 'निकासी के लिए उपलब्ध',
    'total wallet balance:': 'कुल वॉलेट बैलेंस:',
    'under 24-hour security lock': '24 घंटे के सुरक्षा लॉक के अंतर्गत',
    'cashback earned from cash requests is locked for 24 hours to prevent fraud or abuse. once 24 hours elapse, it automatically becomes withdrawable.': 'धोखाधड़ी रोकने के लिए नकद अनुरोधों से अर्जित कैशबैक 24 घंटे के लिए लॉक रहता है। 24 घंटे बाद यह स्वतः निकासी योग्य हो जाता है।',
    '100% secure manual processing': '100% सुरक्षित मैन्युअल प्रोसेसिंग',
    'all withdrawals are reviewed by admin (24-48 hrs)': 'सभी निकासी की एडमिन द्वारा समीक्षा की जाती है (24-48 घंटे)',
    'cashout amount': 'निकासी राशि',
    'min ₹50 · auto-approve up to ₹5,000': 'न्यूनतम ₹50 · ₹5,000 तक स्वतः स्वीकृत',
    'cashout breakdown': 'निकासी विवरण',
    'requested amount:': 'अनुरोधित राशि:',
    'withdrawal fee:': 'निकासी शुल्क:',
    'platform fee (2%):': 'प्लेटफ़ॉर्म शुल्क (2%):',
    'total fee deduction:': 'कुल शुल्क कटौती:',
    'net amount to receive:': 'प्राप्त होने वाली शुद्ध राशि:',
    'withdraw to bank': 'बैंक में निकालें',
    'transferring...': 'ट्रांसफ़र हो रहा है...',
    'withdrawal history': 'निकासी इतिहास',
    'no withdrawals yet': 'अभी तक कोई निकासी नहीं हुई',
    'admin review required': 'एडमिन समीक्षा आवश्यक',
    'locked (24-hr)': 'लॉक (24 घंटे)',
    'withdrawable': 'निकासी योग्य',
    'withdrawable:': 'निकासी योग्य:',
    'instant 12-digit upi claim': 'तत्काल 12-अंकीय UPI दावा',
    "if google pay, phonepe, or paytm didn't send your phone number, enter your 12-digit upi reference / utr number from your payment receipt to claim cashback:": "यदि Google Pay, PhonePe या Paytm ने आपका फ़ोन नंबर नहीं भेजा, तो कैशबैक का दावा करने के लिए अपनी भुगतान रसीद से 12-अंकों का UPI संदर्भ / UTR नंबर दर्ज करें:",
    "if google pay or your upi app didn't share your contact number, enter the 12-digit upi reference no. (utr) from your payment receipt to claim your cashback!": "यदि Google Pay या आपकी UPI ऐप ने आपका नंबर साझा नहीं किया है, तो कैशबैक का दावा करने के लिए अपनी रसीद से 12 अंकों का UPI संदर्भ (UTR) दर्ज करें!",
    '12-digit upi ref no. / utr': '12-अंकीय UPI संदर्भ सं. / UTR',

    // Vendor Wallet Modals & Security Verification
    'withdrawal submitted!': 'निकासी अनुरोध सबमिट हो गया!',
    'your request has been received and will be processed to your bank within 24-48 business hours.': 'आपका अनुरोध प्राप्त हो गया है और 24-48 कार्य घंटों के भीतर बैंक में प्रोसेस कर दिया जाएगा।',
    'transaction receipt': 'लेन-देन रसीद',
    'gross withdrawal:': 'कुल निकासी:',
    'withdrawal fee:': 'निकासी शुल्क:',
    'platform fee (2%):': 'प्लेटफ़ॉर्म शुल्क (2%):',
    'total fee deduction:': 'कुल शुल्क कटौती:',
    'net bank transfer:': 'शुद्ध बैंक ट्रांसफ़र:',
    'destination account': 'गंतव्य बैंक खाता',
    'done & return to wallet': 'संपन्न एवं वॉलेट पर लौटें',
    'update bank account': 'बैंक खाता अपडेट करें',
    'link bank account': 'बैंक खाता लिंक करें',
    'verify mobile otp': 'मोबाइल OTP सत्यापित करें',
    'secure bank details for withdrawal payouts': 'निकासी भुगतान हेतु सुरक्षित बैंक विवरण',
    'two-step security verification': 'दो-चरणीय सुरक्षा सत्यापन',
    'account holder name *': 'खाता धारक का नाम *',
    'bank name *': 'बैंक का नाम *',
    'account number *': 'खाता संख्या *',
    'confirm account *': 'खाता संख्या की पुष्टि करें *',
    'ifsc code *': 'IFSC कोड *',
    'upi id (optional)': 'UPI ID (वैकल्पिक)',
    'continue to otp verification': 'OTP सत्यापन के लिए आगे बढ़ें',
    'sending otp...': 'OTP भेजा जा रहा है...',
    'enter verification code': 'सत्यापन कोड दर्ज करें',
    'we sent a 4-digit code to': 'हमने 4 अंकों का कोड भेजा है',
    '4-digit otp': '4-अंकीय OTP',
    'edit bank details': 'बैंक विवरण बदलें',
    'resend code': 'कोड दोबारा भेजें',
    'verifying otp & saving...': 'OTP सत्यापित और सेव हो रहा है...',
    'verify & link account': 'सत्यापित करें और खाता लिंक करें',
    'to protect your payouts, a 4-digit verification code will be sent to your registered mobile number': 'आपके भुगतान की सुरक्षा के लिए, आपके पंजीकृत मोबाइल नंबर पर 4 अंकों का सत्यापन कोड भेजा जाएगा',
    'security authorization': 'सुरक्षा प्रमाणीकरण',
    'withdrawing': 'निकासी',
    'touch fingerprint or face id': 'फ़िंगरप्रिंट या Face ID स्पर्श करें',
    'authorize transfer on your device': 'अपने डिवाइस पर ट्रांसफ़र अधिकृत करें',
    'verify with biometrics': 'बायोमेट्रिक्स से सत्यापित करें',
    'use pin / password instead': 'पिन / पासवर्ड का उपयोग करें',
    'enter 4-digit security pin': '4-अंकीय सुरक्षा पिन दर्ज करें',
    'verify & confirm cashout': 'सत्यापित करें और निकासी की पुष्टि करें',
    'switch back to biometrics': 'बायोमेट्रिक्स पर वापस जाएं',
    'verified bank': 'सत्यापित बैंक',
    'linked bank': 'लिंक्ड बैंक',
    'registered phone': 'पंजीकृत फ़ोन',
    'to': 'खाते में',
    'destination bank account': 'गंतव्य बैंक खाता',
    'bank account required': 'बैंक खाता आवश्यक',

    // Vendor Pay Later & Credit
    'coming soon • vendor credit': 'जल्द आ रहा है • वेंडर क्रेडिट',
    'vendor shop & pay later': 'वेंडर शॉप व पे लेटर',
    'maintain 30 days transactions & get credit limit upto ₹25,000': '30 दिनों का लेन-देन बनाए रखें और ₹25,000 तक की क्रेडिट लिमिट पाएं',
    'maintain 30 days store transactions to unlock limit based on pan & cibil score': 'PAN और CIBIL स्कोर के आधार पर लिमिट अनलॉक करने के लिए 30 दिनों का स्टोर लेन-देन बनाए रखें',
    'credit limit': 'क्रेडिट लिमिट',
    'upto ₹25,000': '₹25,000 तक',
    'collateral': 'जमानत (Collateral)',
    '0% (collateral-free)': '0% (बिना किसी गारंटी के)',
    '30-day store streak': '30-दिनों का स्टोर स्ट्रीक',
    'store par regular customer payments log karein ya cashback issue karein.': 'दुकान पर नियमित ग्राहक भुगतान रिकॉर्ड करें या कैशबैक जारी करें।',
    'inventory stock': 'इन्वेंट्री स्टॉक',
    'purchase stock on credit': 'क्रेडिट पर स्टॉक खरीदें',
    'pan & cibil': 'PAN और CIBIL',
    'instant paperless approval': 'तत्काल पेपरलेस स्वीकृति',
    'store registered for early access!': 'स्टोर प्रारंभिक एक्सेस के लिए पंजीकृत हो गया!',
    'aapki details receive ho gayi hain. feature live hote hi aur 30-day streak par aapki ₹25,000 credit limit unlock ho jayegi.': 'आपकी जानकारी प्राप्त हो गई है। फ़ीचर लाइव होने और 30-दिन की स्ट्रीक पूरी होने पर ₹25,000 की क्रेडिट लिमिट अनलॉक हो जाएगी।',
    'store / business name': 'दुकान / व्यवसाय का नाम',
    'proprietor / business pan card': 'मालिक / व्यापार का पैन कार्ड',
    'pre-apply & notify me': 'पहले आवेदन करें और मुझे सूचित करें',

    // Vendor Subscription Page
    'store subscription': 'स्टोर सब्सक्रिप्शन',
    'chain & brand': 'चेन और ब्रांड',
    'independent store': 'स्वतंत्र स्टोर',
    'choose a plan to keep your store active, visible on map/search listings, and eligible for customer cashbacks.': 'अपने स्टोर को सक्रिय रखने, सर्च/मैप में दिखाने और ग्राहकों को कैशबैक देने के लिए प्लान चुनें।',
    'welcome offer: +10 days extra validity free!': 'वेलकम ऑफ़र: +10 दिन अतिरिक्त वैधता मुफ़्त!',
    'new merchant special': 'नए दुकानदारों के लिए विशेष',
    'current subscription status': 'वर्तमान सब्सक्रिप्शन स्थिति',
    'visible on map & search': 'मैप और सर्च पर दृश्यमान',
    'hidden from discovery': 'सर्च से छिपा हुआ',
    'cashback wallet balance': 'कैशबैक वॉलेट बैलेंस',
    'recharge wallet': 'वॉलेट रिचार्ज करें',
    'flexible option': 'लचीला विकल्प',
    '1 month plan': '1 महीने का प्लान',
    'pay month-to-month with complete flexibility.': 'पूरी लचीलेपन के साथ महीने-दर-महीने भुगतान करें।',
    '/ 30 days': '/ 30 दिन',
    '+10 days bonus = 40 days total': '+10 दिन बोनस = कुल 40 दिन',
    '+10 days bonus = 100 days total': '+10 दिन बोनस = कुल 100 दिन',
    '+10 days bonus = 375 days total': '+10 दिन बोनस = कुल 375 दिन',
    'plan highlights': 'प्लान की मुख्य विशेषताएं',
    'quarterly boost': 'त्रैमासिक बूस्ट',
    '3 months plan': '3 महीने का प्लान',
    'most popular · save ~13%': 'सबसे लोकप्रिय · ~13% बचाएं',
    'steady customer footfall with quarterly savings.': 'त्रैमासिक बचत के साथ ग्राहकों का निरंतर आना-जाना।',
    '/ 90 days': '/ 90 दिन',
    'full year growth': 'पूरे साल की ग्रोथ',
    'yearly plan': 'वार्षिक प्लान',
    'best value · 2 mo free': 'सर्वश्रेष्ठ मूल्य · 2 महीने मुफ़्त',
    'uninterrupted listing with priority discovery boost.': 'प्राथमिकता डिस्कवरी बूस्ट के साथ निर्बाध लिस्टिंग।',
    '/ 365 days': '/ 365 दिन',
    'all 1 month plan features': '1 महीने के प्लान की सभी सुविधाएं',
    'save ~13% on quarterly billing': 'त्रैमासिक बिलिंग पर ~13% बचाएं',
    'priority listing in search results': 'सर्च परिणामों में प्राथमिकता लिस्टिंग',
    'enhanced business analytics': 'उन्नत व्यावसायिक विश्लेषण',
    'priority merchant support': 'प्राथमिकता मर्चेंट सहायता',
    'all 3 months plan features': '3 महीने के प्लान की सभी सुविधाएं',
    '2 months free (save ~17%)': '2 महीने मुफ़्त (~17% बचाएं)',
    'top priority placement in search': 'सर्च में सर्वोच्च प्राथमिकता प्लेसमेंट',
    'dedicated account manager': 'समर्पित अकाउंट मैनेजर',
    'promotional banners on zeebac': 'ZeeBac पर प्रमोशनल बैनर',
    'select payment method': 'भुगतान विधि चुनें',
    'amount payable:': 'देय राशि:',
    'validity:': 'वैधता:',
    'pay via razorpay': 'Razorpay से भुगतान करें',
    'upi, cards, netbanking & wallets': 'UPI, कार्ड, नेटबैंकिंग और वॉलेट',
    'pay from wallet': 'वॉलेट से भुगतान करें',
    'instant activation using in-app balance': 'ऐप बैलेंस से तत्काल सक्रियण',
    'current wallet balance:': 'वर्तमान वॉलेट बैलेंस:',
    'subscription price:': 'सब्सक्रिप्शन मूल्य:',
    'remaining balance after payment:': 'भुगतान के बाद शेष बैलेंस:',
    'insufficient wallet balance. please recharge your wallet or pay using razorpay.': 'अपर्याप्त वॉलेट बैलेंस। कृपया अपना वॉलेट रिचार्ज करें या Razorpay से भुगतान करें।',
    '256-bit encrypted & verified': '256-बिट एन्क्रिप्टेड और सत्यापित',

    // Vendor Onboarding & Application Status
    'vendor partner': 'वेंडर पार्टनर',
    'grow your business with zeebac': 'ZeeBac के साथ अपना व्यवसाय बढ़ाएं',
    'list your store, offer cashback to customers, and watch your customer base grow.': 'अपने स्टोर को सूचीबद्ध करें, ग्राहकों को कैशबैक दें, और अपने ग्राहकों की संख्या बढ़ते देखें।',
    'qr payments': 'QR भुगतान',
    'customer base': 'ग्राहक आधार',
    'cashback tools': 'कैशबैक टूल्स',
    'sign in to vendor portal': 'वेंडर पोर्टल में साइन इन करें',
    'register your business': 'अपना व्यवसाय पंजीकृत करें',
    'application status': 'आवेदन की स्थिति',
    '🟡 under review': '🟡 समीक्षाधीन',
    '🟡 resubmitted — under review': '🟡 पुनः सबमिट किया गया — समीक्षाधीन',
    '🎉 onboarding completed': '🎉 ऑनबोर्डिंग पूर्ण',
    'your application is not yet submitted. continue where you left off.': 'आपका आवेदन अभी सबमिट नहीं हुआ है। जहां छोड़ा था वहां से जारी रखें।',
    'your vendor application has been submitted and is currently being reviewed by the zeebac admin team.': 'आपका वेंडर आवेदन सबमिट हो गया है और वर्तमान में ZeeBac एडमिन टीम द्वारा समीक्षाधीन है।',
    'your updated application has been resubmitted and is being reviewed by the zeebac admin team.': 'आपका संशोधित आवेदन पुनः सबमिट हो गया है और ZeeBac एडमिन टीम द्वारा समीक्षाधीन है।',
    'your vendor application has been approved! purchase a subscription to activate your store and start receiving customers.': 'आपका वेंडर आवेदन स्वीकृत हो गया है! अपना स्टोर सक्रिय करने और ग्राहकों को आकर्षित करने के लिए सब्सक्रिप्शन लें।',
    'approved cashback': 'स्वीकृत कैशबैक',
    'submitted on': 'सबमिट करने की तिथि',
    'store status': 'दुकान की स्थिति',
    'subscription required': 'सब्सक्रिप्शन आवश्यक',
    'choose subscription plan': 'सब्सक्रिप्शन प्लान चुनें',
    'continue application': 'आवेदन जारी रखें',
    'log out': 'लॉग आउट',
    'application rejected': 'आवेदन अस्वीकृत',
    'your vendor application needs a few corrections before it can be approved.': 'आपके वेंडर आवेदन में स्वीकृत होने से पहले कुछ सुधारों की आवश्यकता है।',
    'review & update application': 'आवेदन की समीक्षा करें और अपडेट करें',
    'review changes': 'परिवर्तनों की समीक्षा करें',
    'resubmit application': 'आवेदन पुनः सबमिट करें',
    'no changes': 'कोई बदलाव नहीं',
    'business type': 'व्यवसाय का प्रकार',
    'sub-category': 'उप-श्रेणी',
    'customer cashback (%)': 'ग्राहक कैशबैक (%)',
    'business contact number': 'व्यापारिक संपर्क नंबर',
    'business email': 'व्यापारिक ईमेल',
    'owner id / kyc document': 'मालिक पहचान पत्र / KYC दस्तावेज़',
    'shop registration document': 'दुकान पंजीकरण दस्तावेज़',
    'cancelled cheque': 'कैंसिल्ड चेक',
    'additional document': 'अतिरिक्त दस्तावेज़',
    'map location': 'मैप पर स्थान',
    'store cover image': 'स्टोर कवर फ़ोटो',
    'step': 'चरण',
    'of': 'का',
    'account': 'खाता',
    'business': 'व्यवसाय',
    'documents': 'दस्तावेज़',
    'review': 'समीक्षा',
    'saving...': 'सहेजा जा रहा है...',
    'continue': 'आगे बढ़ें'
  }
};

const getSavedLanguage = () => {
  try {
    const saved = localStorage.getItem('zeebac_app_language');
    if (saved === 'hi' || saved === 'en') return saved;
  } catch (e) {
    // ignore
  }
  return 'en';
};

export const useLanguageStore = create((set, get) => ({
  language: getSavedLanguage(),
  supportedLanguages: SUPPORTED_LANGUAGES,

  setLanguage: (langCode) => {
    if (langCode === 'en' || langCode === 'hi') {
      try {
        localStorage.setItem('zeebac_app_language', langCode);
      } catch (e) {
        // ignore
      }
      set({ language: langCode });
    }
  },

  // Smart translation function
  // Accepts either a translation key or raw English text and returns Hindi ONLY if explicitly selected
  t: (textOrKey, fallback = '') => {
    if (!textOrKey) return fallback || '';

    // 1. Admin panel is strictly English only — never translate to Hindi in admin
    if (typeof window !== 'undefined' && window.location.pathname.startsWith('/admin')) {
      return textOrKey;
    }

    // 2. Default to English: If language is 'en', ALWAYS return the original English text
    const lang = get().language || 'en';
    if (lang === 'en') {
      return textOrKey;
    }

    // 3. User or Vendor explicitly selected Hindi ('hi')
    const dict = translations.hi || {};

    // 3a. Direct key match
    if (dict[textOrKey] !== undefined) {
      return dict[textOrKey];
    }

    // 3b. Normalized lowercase match
    const normalized = String(textOrKey).trim().toLowerCase();
    if (dict[normalized] !== undefined) {
      return dict[normalized];
    }

    return fallback || textOrKey;
  }
}));

export default useLanguageStore;
